### ISSUE TITLE
Build explodes with yarn 3

### ISSUE THREAD

**Issue by weeman1337** [vector-im/compound#156]
Raising this issue because we are using Compound in a yarn 3 project.

Steps to reproduce:

- Switch to yarn 3
- `yarn`
- `yarn run build`

Result:

```
~/git/element/compound-web (main)$ yarn run build

[vite:dts] You are building a library that may not need to generate declaration files.

vite v4.3.5 building for production...
✓ 17 modules transformed.

[vite:dts] Start generate declaration files...
✓ built in 2.20s
transforming (18) src/components/Form/ValidityState.tsx[vite:dts] Declaration files built in 2123ms.

[vite]: Rollup failed to resolve import "@vector-im/compound-design-tokens/icons/check-circle.svg" from "/home/michaelw/git/element/compound-web/src/components/Alert/Alert.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@vector-im/compound-design-tokens/icons/check-circle.svg" from "/home/michaelw/git/element/compound-web/src/components/Alert/Alert.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/michaelw/git/element/compound-web/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:46561:23)
    at onwarn (file:///home/michaelw/git/element/compound-web/node_modules/@vitejs/plugin-react/dist/index.mjs:237:9)
    at onRollupWarning (file:///home/michaelw/git/element/compound-web/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:46582:9)
    at onwarn (file:///home/michaelw/git/element/compound-web/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:46332:13)
    at Object.onwarn (file:///home/michaelw/git/element/compound-web/node_modules/rollup/dist/es/shared/node-entry.js:25305:13)
    at ModuleLoader.handleInvalidResolvedId (file:///home/michaelw/git/element/compound-web/node_modules/rollup/dist/es/shared/node-entry.js:23940:26)
    at file:///home/michaelw/git/element/compound-web/node_modules/rollup/dist/es/shared/node-entry.js:23900:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by weeman1337** [comment]
Don't know if this is really an issue. We manage to fix it on the user side. @germain-gg feel free to close it.
